namespace Parser.Binding
{
    public enum BoundBinaryOperatorKind
    {
        Equals,
        PipePipe,
        AmpersandAmpersand,
        Pipe,
        Ampersand,
        Less,
        LessOrEquals,
        Greater,
        GreaterOrEquals,
        EqualsEquals,
        TildeEquals,
        Colon,
        Plus,
        Minus,
        Star,
        DotStar,
        Slash,
        DotSlash,
        Backslash,
        DotBackslash,
        Tilde,
        Caret,
        DotCaret,
        LessInt,
        PlusInt,
    }
}
